name: Spring Framework Test

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        distribution: [ubuntu]

    inputs:
      distribution:
        description: 'The Linux distribution to use'
        required: true
        default: ${{ matrix.distribution }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 17 with Maven
        uses: actions/setup-java@v2
        with:
          java-version: 17
          maven-version: 3.8.3

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn test --file pom.xml
